server:
  port: 8080
  max-http-header-size: 16KB
  shutdown: graceful

spring:
  application:
    name: blog-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 1000
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  redis:
    host: localhost
    port: 6379

---
spring:
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000
    username: root
    password: 1q2w3e4r