server:
  port: 8080
  max-http-header-size: 16KB
  shutdown: graceful

spring:
  application:
    name: blog-code
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 20
      connection-timeout: 1000
      leak-detection-threshold: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  redis:
    host: localhost
    port: 6379

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true

management:
  endpoints:
    web:
      exposure:
        include:
          - "*" # 테스트를 위해 actuator 전체 노출

  health:
    circuitbreakers:
      enabled: true # circuitbreakers 정보 노출
---
spring:
  config:
    activate:
      on-profile: default
  jpa:
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=UTF-8&connectTimeout=60000&socketTimeout=60000
    username: root
    password: 1q2w3e4r